spring:
  docker:
    compose:
      enabled: false

  profiles:
    include: secret

  datasource:
    url: jdbc:mariadb://13.125.136.73:3306/fashion_game?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false&tcpKeepAlive=true&connectTimeout=60000&socketTimeout=60000
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: update # 엔티티 변경 시 DB 테이블 자동 생성/수정
    show-sql: true     # 실행되는 SQL을 콘솔에 출력
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379
  
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID} # 발급받은 클라이언트 ID
            client-secret: ${GOOGLE_CLIENT_SECRET} # 발급받은 시크릿 키
            scope:
              - email
              - profile

jwt:
  secret: ${JWT_SECRET}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}
    region:
      static: ap-northeast-2
    stack:
      auto: false