"use client";

export function PatternBackground({
  type = "hearts",
}: {
  type?: "hearts" | "stars" | "mixed";
}) {
  return (
    <svg
      className="absolute inset-0 h-full w-full opacity-50"
      style={{ imageRendering: "pixelated" }}
      aria-hidden="true"
    >
      <defs>
        {/* Pixelated Heart pattern - low quality */}
        <pattern
          id="hearts-pattern"
          x="0"
          y="0"
          width="50"
          height="50"
          patternUnits="userSpaceOnUse"
        >
          {/* Simple pixelated heart made of rectangles */}
          <rect
            x="10"
            y="15"
            width="5"
            height="5"
            fill="#ff69b4"
          />
          <rect
            x="20"
            y="15"
            width="5"
            height="5"
            fill="#ff69b4"
          />
          <rect
            x="5"
            y="20"
            width="5"
            height="5"
            fill="#ff69b4"
          />
          <rect
            x="10"
            y="20"
            width="5"
            height="5"
            fill="#ff69b4"
          />
          <rect
            x="15"
            y="20"
            width="5"
            height="5"
            fill="#ff69b4"
          />
          <rect
            x="20"
            y="20"
            width="5"
            height="5"
            fill="#ff69b4"
          />
          <rect
            x="25"
            y="20"
            width="5"
            height="5"
            fill="#ff69b4"
          />
          <rect
            x="5"
            y="25"
            width="5"
            height="5"
            fill="#ff69b4"
          />
          <rect
            x="10"
            y="25"
            width="5"
            height="5"
            fill="#ff69b4"
          />
          <rect
            x="15"
            y="25"
            width="5"
            height="5"
            fill="#ff69b4"
          />
          <rect
            x="20"
            y="25"
            width="5"
            height="5"
            fill="#ff69b4"
          />
          <rect
            x="25"
            y="25"
            width="5"
            height="5"
            fill="#ff69b4"
          />
          <rect
            x="10"
            y="30"
            width="5"
            height="5"
            fill="#ff69b4"
          />
          <rect
            x="15"
            y="30"
            width="5"
            height="5"
            fill="#ff69b4"
          />
          <rect
            x="20"
            y="30"
            width="5"
            height="5"
            fill="#ff69b4"
          />
          <rect
            x="15"
            y="35"
            width="5"
            height="5"
            fill="#ff69b4"
          />

          {/* Yellow flower/dot accents */}
          <rect
            x="38"
            y="8"
            width="8"
            height="8"
            fill="#ffd700"
          />
          <rect
            x="42"
            y="4"
            width="4"
            height="4"
            fill="#ffd700"
          />
          <rect
            x="38"
            y="12"
            width="4"
            height="4"
            fill="#ffd700"
          />
          <rect
            x="46"
            y="12"
            width="4"
            height="4"
            fill="#ffd700"
          />
        </pattern>

        {/* Pixelated Star pattern - low quality */}
        <pattern
          id="stars-pattern"
          x="0"
          y="0"
          width="55"
          height="55"
          patternUnits="userSpaceOnUse"
        >
          {/* Simple pixelated star made of rectangles */}
          <rect
            x="20"
            y="10"
            width="6"
            height="6"
            fill="#fbbf24"
          />
          <rect
            x="17"
            y="16"
            width="6"
            height="6"
            fill="#fbbf24"
          />
          <rect
            x="23"
            y="16"
            width="6"
            height="6"
            fill="#fbbf24"
          />
          <rect
            x="11"
            y="22"
            width="6"
            height="6"
            fill="#fbbf24"
          />
          <rect
            x="17"
            y="22"
            width="6"
            height="6"
            fill="#fbbf24"
          />
          <rect
            x="23"
            y="22"
            width="6"
            height="6"
            fill="#fbbf24"
          />
          <rect
            x="29"
            y="22"
            width="6"
            height="6"
            fill="#fbbf24"
          />
          <rect
            x="17"
            y="28"
            width="6"
            height="6"
            fill="#fbbf24"
          />
          <rect
            x="23"
            y="28"
            width="6"
            height="6"
            fill="#fbbf24"
          />

          {/* Pink flower/dot accents */}
          <rect
            x="40"
            y="40"
            width="8"
            height="8"
            fill="#ff69b4"
          />
          <rect
            x="44"
            y="36"
            width="4"
            height="4"
            fill="#ff69b4"
          />
          <rect
            x="40"
            y="44"
            width="4"
            height="4"
            fill="#ff69b4"
          />
          <rect
            x="48"
            y="44"
            width="4"
            height="4"
            fill="#ff69b4"
          />
        </pattern>

        {/* Mixed pixelated pattern - low quality */}
        <pattern
          id="mixed-pattern"
          x="0"
          y="0"
          width="80"
          height="80"
          patternUnits="userSpaceOnUse"
        >
          {/* Pink pixelated heart 1 */}
          <rect
            x="8"
            y="12"
            width="4"
            height="4"
            fill="#ff69b4"
          />
          <rect
            x="16"
            y="12"
            width="4"
            height="4"
            fill="#ff69b4"
          />
          <rect
            x="4"
            y="16"
            width="4"
            height="4"
            fill="#ff69b4"
          />
          <rect
            x="8"
            y="16"
            width="4"
            height="4"
            fill="#ff69b4"
          />
          <rect
            x="12"
            y="16"
            width="4"
            height="4"
            fill="#ff69b4"
          />
          <rect
            x="16"
            y="16"
            width="4"
            height="4"
            fill="#ff69b4"
          />
          <rect
            x="20"
            y="16"
            width="4"
            height="4"
            fill="#ff69b4"
          />
          <rect
            x="8"
            y="20"
            width="4"
            height="4"
            fill="#ff69b4"
          />
          <rect
            x="12"
            y="20"
            width="4"
            height="4"
            fill="#ff69b4"
          />
          <rect
            x="16"
            y="20"
            width="4"
            height="4"
            fill="#ff69b4"
          />
          <rect
            x="12"
            y="24"
            width="4"
            height="4"
            fill="#ff69b4"
          />

          {/* Yellow flower accent 1 */}
          <rect
            x="28"
            y="10"
            width="6"
            height="6"
            fill="#ffd700"
          />
          <rect
            x="31"
            y="7"
            width="3"
            height="3"
            fill="#ffd700"
          />
          <rect
            x="28"
            y="13"
            width="3"
            height="3"
            fill="#ffd700"
          />
          <rect
            x="34"
            y="13"
            width="3"
            height="3"
            fill="#ffd700"
          />

          {/* Yellow pixelated heart 2 */}
          <rect
            x="58"
            y="52"
            width="4"
            height="4"
            fill="#fde047"
          />
          <rect
            x="66"
            y="52"
            width="4"
            height="4"
            fill="#fde047"
          />
          <rect
            x="54"
            y="56"
            width="4"
            height="4"
            fill="#fde047"
          />
          <rect
            x="58"
            y="56"
            width="4"
            height="4"
            fill="#fde047"
          />
          <rect
            x="62"
            y="56"
            width="4"
            height="4"
            fill="#fde047"
          />
          <rect
            x="66"
            y="56"
            width="4"
            height="4"
            fill="#fde047"
          />
          <rect
            x="70"
            y="56"
            width="4"
            height="4"
            fill="#fde047"
          />
          <rect
            x="58"
            y="60"
            width="4"
            height="4"
            fill="#fde047"
          />
          <rect
            x="62"
            y="60"
            width="4"
            height="4"
            fill="#fde047"
          />
          <rect
            x="66"
            y="60"
            width="4"
            height="4"
            fill="#fde047"
          />
          <rect
            x="62"
            y="64"
            width="4"
            height="4"
            fill="#fde047"
          />

          {/* Yellow flower accent 2 */}
          <rect
            x="72"
            y="35"
            width="6"
            height="6"
            fill="#ffd700"
          />
          <rect
            x="75"
            y="32"
            width="3"
            height="3"
            fill="#ffd700"
          />
          <rect
            x="72"
            y="38"
            width="3"
            height="3"
            fill="#ffd700"
          />
          <rect
            x="78"
            y="38"
            width="3"
            height="3"
            fill="#ffd700"
          />

          {/* Pink pixelated star */}
          <rect
            x="56"
            y="8"
            width="5"
            height="5"
            fill="#ec4899"
          />
          <rect
            x="53"
            y="13"
            width="5"
            height="5"
            fill="#ec4899"
          />
          <rect
            x="59"
            y="13"
            width="5"
            height="5"
            fill="#ec4899"
          />
          <rect
            x="48"
            y="18"
            width="5"
            height="5"
            fill="#ec4899"
          />
          <rect
            x="53"
            y="18"
            width="5"
            height="5"
            fill="#ec4899"
          />
          <rect
            x="59"
            y="18"
            width="5"
            height="5"
            fill="#ec4899"
          />
          <rect
            x="64"
            y="18"
            width="5"
            height="5"
            fill="#ec4899"
          />
          <rect
            x="53"
            y="23"
            width="5"
            height="5"
            fill="#ec4899"
          />
          <rect
            x="59"
            y="23"
            width="5"
            height="5"
            fill="#ec4899"
          />

          {/* Yellow flower accent 3 */}
          <rect
            x="10"
            y="65"
            width="6"
            height="6"
            fill="#ffd700"
          />
          <rect
            x="13"
            y="62"
            width="3"
            height="3"
            fill="#ffd700"
          />
          <rect
            x="10"
            y="68"
            width="3"
            height="3"
            fill="#ffd700"
          />
          <rect
            x="16"
            y="68"
            width="3"
            height="3"
            fill="#ffd700"
          />

          {/* Cyan pixelated star */}
          <rect
            x="28"
            y="42"
            width="5"
            height="5"
            fill="#22d3ee"
          />
          <rect
            x="25"
            y="47"
            width="5"
            height="5"
            fill="#22d3ee"
          />
          <rect
            x="31"
            y="47"
            width="5"
            height="5"
            fill="#22d3ee"
          />
          <rect
            x="20"
            y="52"
            width="5"
            height="5"
            fill="#22d3ee"
          />
          <rect
            x="25"
            y="52"
            width="5"
            height="5"
            fill="#22d3ee"
          />
          <rect
            x="31"
            y="52"
            width="5"
            height="5"
            fill="#22d3ee"
          />
          <rect
            x="36"
            y="52"
            width="5"
            height="5"
            fill="#22d3ee"
          />
          <rect
            x="25"
            y="57"
            width="5"
            height="5"
            fill="#22d3ee"
          />
          <rect
            x="31"
            y="57"
            width="5"
            height="5"
            fill="#22d3ee"
          />

          {/* Yellow flower accent 4 */}
          <rect
            x="42"
            y="68"
            width="7"
            height="7"
            fill="#ffd700"
          />
          <rect
            x="45"
            y="65"
            width="3"
            height="3"
            fill="#ffd700"
          />
          <rect
            x="42"
            y="72"
            width="3"
            height="3"
            fill="#ffd700"
          />
          <rect
            x="49"
            y="72"
            width="3"
            height="3"
            fill="#ffd700"
          />
        </pattern>

        {/* Small dots pattern - very pixelated */}
        <pattern
          id="dots-pattern"
          x="0"
          y="0"
          width="25"
          height="25"
          patternUnits="userSpaceOnUse"
        >
          <rect
            x="10"
            y="10"
            width="5"
            height="5"
            fill="#ff1493"
            opacity="0.5"
          />
        </pattern>
      </defs>

      <rect
        width="100%"
        height="100%"
        fill={`url(#${type}-pattern)`}
      />
    </svg>
  );
}
